{% set name = "pycodestyle" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycodestyle-{{ version }}.tar.gz
  sha256: beaba44501f89d785be791c9462553f06958a221d166c64e1f107320f839acc2

build:
  entry_points:
    - pycodestyle = pycodestyle:_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pycodestyle
  commands:
    - pip check
    - pycodestyle --help
  requires:
    - pip

about:
  home: https://pycodestyle.readthedocs.io/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Python style guide checker
  doc_url: https://pycodestyle.readthedocs.io/
  dev_url: https://github.com/PyCQA/pycodestyle

extra:
  recipe-maintainers:
    - jakirkham
    - sigmavirus24
    - dopplershift
    - ocefpaf
