{% set name = "pycodestyle" %}
{% set version = "2.7.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "c389c1d06bf7904078ca03399a4816f974a1d590090fecea0c63ec26ebaf1cef" %}
{% set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - pycodestyle = pycodestyle:_main

  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - pycodestyle --help
    - pycodestyle --version

about:
  home: https://pycodestyle.readthedocs.io/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Python style guide checker
  doc_url: https://pycodestyle.readthedocs.io/
  dev_url: https://github.com/PyCQA/pycodestyle

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - jjhelmus
    - sigmavirus24
    - dopplershift
    - ocefpaf
